### ISSUE TITLE
Consistency within Printing Profiles

### ISSUE THREAD

**Issue by TeaObvious** [beeverycreative/B2X300-resources#2]
I wanted to create my self a PLA_PTEG profile based on the profiles from the github.
As a starting point i compared all profiles and found that the PTEG and PLA profiles are very similar, which made me happy. 
Only the PVA Profiles differ a lot from the other Profiles, even the PLA Extruder Profile differs between the PLA_PVA and the  PLA_PLA Profile.

How ever then i compared the files of extruder 1 and extruder 2 (same profile) i saw that they are very different. With values defined in 2 that are not defined in 1.

**So my question is, why are the profiles for extruder 1 and extruder 2 so much different for the same Material?**

**Comment by DomingosRodrigues** [comment]
Hello Legodev,

The PVA -PLA profile should use a more conservative print settings to avoid any issues when using the soluble filament PVA, that is slightly prone to some underextrusion and even adhesion issues between the materials if the filament hasn't been properly conditioned and has moisture in it. 

Just a heads up you should use the latest profile for MCPP filament as reference as they are slightly more updated.

PLA + PETG in our tests shouldn't adhere to each other so be careful when printing with that combo to avoid problems. It can be used to support large bridges and other supports that support directly from the build platform.

**Comment by TeaObvious** [comment]
Hello DomingosRodrigues,
thank you very much for that answer! :)

The PLA + PETG Combination is intended to be used for easy to remove supports, as i want to experiment with this technique once i finally got my B2X300 and got it properly setup and tested.

So based on your answer, i should be fine to for example take the PLA Extruder profile of the MCPP profile and simply apply it to both Extruders to get a PLA-PLA profile? - As this was my core question i was wondering about, why the settings for Extruder 1 and Extruder 2 differ in the each of the original profiles such as PLA_PLA. :)

**Comment by DomingosRodrigues** [comment]
Hello Legodev,

Yes using the same settings on both extruders as the E1 configs for PLA MCPP should be the correct configuration for PLA PLA.

In which profile file did you find the error in configuration and what settings are different? I would like to take a look into the issue.
Not sure if it is the case but it might be a compatibility issue with the latest cura and the profile that was generate in an older cura version that is causing the profile to be misread.

**Comment by TeaObvious** [comment]
Hello DomingosRodrigues,

what i am talking about is related to the other issue report: https://github.com/beeverycreative/B2X300-resources/issues/1#issuecomment-590029526

I downloaded the profile, extracted it and compared the extruder profile 1 to 2, where i expected to only find the `position = ` to be different, how ever there are way more differences:

- different acceleration definitions
- additional coasting, infill defintions
- different layer heights from the "master file"
- different print temperature definitions
- different retraction definition
...

Steps to reproduce:
1. downloaded https://github.com/beeverycreative/B2X300-resources/raw/master/Printing_Profiles/B2X300_Cura_Profiles/B2X300_PLA_PLA_v1.2.curaprofile
2. unziped the profile
3. diff "custom_extruder_1_b2x300_pla_pla_v1.1" "custom_extruder_2_b2x300_pla_pla_v1.1"
result: [diff.txt](https://github.com/beeverycreative/B2X300-resources/files/5401480/diff.txt)

Edit: this applied to all v1.2 cura profiles.

**Comment by DomingosRodrigues** [comment]
Thanks for the information Legodev, the profiles should be equal on both extruders!

I will analyze the issue in the following days and reupload the correct and updated profiles!

In the meantime please use the MCPP settings and copy the setting from E1 to E2 and all should work as expected.

**Comment by DomingosRodrigues** [comment]
Hello @Legodev ,

The problem should be solved on the new version of the profiles published on commit 2f299cd76c647b51af205889737bad595d0f22b2

I will wait for your feedback to close the issue

**Comment by TeaObvious** [comment]
Hello @DomingosRodrigues 
for me the question was already solved once i got the answer that both profiles are intended to be identical (except for the position).

How ever i did take a look over the new profiles, and they are much easier to understand now and don't create any confusion, especially the folder structure is superb! :)

I call this issue solved, thank you very much that you took me serious. I am looking forward to use your work. :+1: 

Have a very good time!
Legodev

**Comment by DomingosRodrigues** [comment]
@Legodev Thanks for your feedback!

FYI I've also added some new 3d printed parts for the B2X300 the Frame feet :)

Best regards
